# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/RAM_Input/RAM_Input.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RAM_Input || ORIG_REF_NAME==RAM_Input} -quiet] -quiet
