`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Company: 
// Engineer: 
// 
// Create Date: 11/28/2025 02:34:53 AM
// Design Name: 
// Module Name: tb_ternary_nanocore
// Project Name: 
// Target Devices: 
// Tool Versions: 
// Description: 
// 
// Dependencies: 
// 
// Revision:
// Revision 0.01 - File Created
// Additional Comments:
// 
//////////////////////////////////////////////////////////////////////////////////


module tb_ternary_nanocore;

    // --- 1. Inputs (Regs) ---
    reg clk;
    reg rst_n;
    reg start_btn;

    // --- 2. Outputs (Wires) ---
    wire done_led;
    wire [3:0] led_results;

    // --- 3. Instantiate the Unit Under Test (UUT) ---
    ternary_nanocore_top uut (
        .clk(clk), 
        .rst_n(rst_n), 
        .start_btn(start_btn), 
        .done_led(done_led), 
        .led_results(led_results)
    );
    
    // --- 4. Clock Generation ---
    // Generate a 100MHz clock (Period = 10ns)
    initial begin
        clk = 0;
        forever #5 clk = ~clk;
    end

    // --- 5. The Test Sequence ---
    initial begin
        // Initialize Inputs
        rst_n = 0;       // Hold Reset Active (Low)
        start_btn = 0;
        
        $display("Starting Simulation...");

        // Wait 100 ns for global reset to finish
        #100;
        rst_n = 1;       // Release Reset (System is now ready)
        #20;

        // Press the Start Button
        $display("Pressing Start Button...");
        start_btn = 1;
        #20;             // Hold for 2 clock cycles
        start_btn = 0;   // Release

        // Wait for the "Done" signal to go High
        // The calculation should take roughly: 
        // 10 neurons * 157 steps = 1570 clock cycles
        // plus some overhead.
        wait(done_led == 1);
        
        // Add a small delay to let signals settle
        #20;

        // Print the Result to the Console
        $display("-----------------------------------------");
        $display("Inference Completed Successfully!");
        $display("Predicted Class (LED Output): %d", led_results);
        
        // Compare with expected result if you know the image
        // (Check the selected_image.png generated by Python to verify!)
        $display("-----------------------------------------");

        // End Simulation
        $finish;
    end

    // --- 6. Watchdog Timer (Safety) ---
    // If logic is broken and 'done' never triggers, stop after some time.
// --- 5. The Test Sequence ---
    initial begin
        // Initialize Inputs
        rst_n = 0;       
        start_btn = 0;
        
        $display("Starting Simulation...");
        $display("-----------------------------------------");

        // Reset Sequence
        #100;
        rst_n = 1;       
        #20;

        // Start Pulse
        $display("Pressing Start Button...");
        start_btn = 1;
        #20;             
        start_btn = 0;   

        // --- SPY MODE: PRINT SCORES FOR ALL 10 NEURONS ---
        // We assume there are 10 classes (0 to 9). 
        // We wait for the controller to finish each one.
        
        repeat(10) begin
            // Wait for Controller to enter state 2 (NEXT_NEURON)
            // This means the accumulator is full and valid.
            wait(uut.controller.state == 2); 
            
            // Print the Score!
            $display("Debug: Neuron %d | Score: %d", 
                     uut.controller.neuron_idx, 
                     uut.controller.neuron_accumulator);
            
            // Wait for a clock edge to let the state transition happen
            @(posedge clk);
            
            // Wait until we leave state 2 (so we don't print the same neuron twice)
            wait(uut.controller.state != 2);
        end
        // ------------------------------------------------

        // Wait for final Done signal
        wait(done_led == 1);
        #20;

        // Print Final Result
        $display("-----------------------------------------");
        $display("Inference Completed.");
        $display("Final Winner (LED Output): %d", led_results);
        $display("-----------------------------------------");

        $finish;
    end
    

endmodule
