# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/zahid/Desktop/Projects/Ternary/Ternary-NanoCore/Ternary-NanoCore/HDL/Ternary-NanoCore/Ternary-NanoCore.srcs/sources_1/ip/RAM_Input/RAM_Input.xci
# IP: The module: 'RAM_Input' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/zahid/Desktop/Projects/Ternary/Ternary-NanoCore/Ternary-NanoCore/HDL/Ternary-NanoCore/Ternary-NanoCore.gen/sources_1/ip/RAM_Input/RAM_Input_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM_Input'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/zahid/Desktop/Projects/Ternary/Ternary-NanoCore/Ternary-NanoCore/HDL/Ternary-NanoCore/Ternary-NanoCore.srcs/sources_1/ip/RAM_Input/RAM_Input.xci
# IP: The module: 'RAM_Input' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/zahid/Desktop/Projects/Ternary/Ternary-NanoCore/Ternary-NanoCore/HDL/Ternary-NanoCore/Ternary-NanoCore.gen/sources_1/ip/RAM_Input/RAM_Input_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM_Input'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
